accounts/urls.py
from django.urls import path
from .views import signup, employee_login, logout_view

app_name = 'accounts'

urlpatterns = [

    path('signup/', signup, name='signup'),
    path('login/', employee_login, name='login'),
    path('logout/', logout_view, name='logout'),


]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from rest_framework import routers
from jobs import views

router = routers.DefaultRouter()
router.register(r'JobListing', views.JobListingViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', home, name='home'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [

    path('article/<int:pk>/', PostDetailView.as_view(), name="govtpv"),

    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('govt/', govt, name='govt'),
    path('govtpv/', govt, name='govtpv'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/', apply_job, name='apply'),

]

templates/base.html
{% load static %}


<html lang="en">
  <head>
    <title>Careers </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
       {% block styles %}{% endblock %}


  </head>
  <body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
{% include 'navbar.html' %}

 {% block content %}

 {% endblock %}


    <section class="py-5 bg-image overlay-primary fixed overlay" >
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8">
            <h2 class="text-white">Looking For A Job?</h2>
            <p class="mb-0 text-white lead">click the sign up to quick start the dream job search</p>
              </p>
          </div>
          <div class="col-md-3 ml-auto">
            <a href="{% url 'accounts:signup' %}" class="btn btn-warning btn-block btn-lg">Sign Up</a>
          </div>
        </div>
      </div>
    </section>
    

  
  </div>

    <!-- SCRIPTS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/stickyfill.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    
    <script src="{% static 'js/custom.js' %}"></script>
{% block javascripts %}{% endblock %}
     
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <!-- HOME -->
    <section class="home-section section-hero overlay bg-image"  style="background-image: url('{% static 'images/careers2.jpg' %}');" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">A Career Website </h1>
              <p>Find your dream jobs in our career website </p>
            </div>
            <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="search-jobs-form">
              <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input type="text"  id="title" name="title" class="form-control form-control-lg" placeholder=" Software Engineer ... ">
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input    type="text" id="job_location" name="job_location" class="form-control form-control-lg" placeholder="Organization">
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select id="employment_status" name="employment_status" class="form-control">
                    <option>Full Time</option>
                  </select>
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>


    </section>

    <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2 text-white">Careers Statistics</h2>
            <p class="lead text-white"></p>
          </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">


          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="" data-number="{{ job_qs }}">  </strong>
            </div>
            <span class="caption"> </span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ candidates }}">0</strong>
            </div>
            <span class="caption">Users</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ job_qs }}"> 0 </strong>
            </div>
            <span class="caption"> Jobs Posted</span>
          </div>



        </div>
      </div>
    </section>













{% endblock %}

templates/navbar.html
{% load static %}



<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="{% url 'home' %}">Careers</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="{% url 'home' %}" class="nav-link active">Home</a></li>
          <li><a href="{% url 'jobs:job-listing' %}">Job Listings</a></li>
          <li><a href="{% url 'jobs:contact' %}">Contact</a></li>


          <li class="d-lg-none"><a href="#">Contact Us</a></li>
        </ul>
      </nav>
{% if user.is_authenticated %}
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">


          <ul class="nav nav-tabs">

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="True" aria-expanded="false">
      {{request.user.first_name}} {{request.user.last_name}}</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>

    </div>
  </li>


</ul>




        </div>
      </div>



{% endif %}
    </div>
  </div>
    </header>